### ISSUE TITLE
remove `<!DOCTYPE html>` at the beginning

### ISSUE THREAD

**Issue by khoivan88** [vimtor/eleventy-plugin-external-links#1]
Hi,

Thank you very much for this useful extension. I noticed that this script add `<!DOCTYPE html>` at the beginning of the document which I think is unnecessary (might not need it or already exists). I was just wondering if there is an option to turn this off or maybe your reason to add it there?

Thank you very much!

Best!

**Comment by vimtor** [comment]
Hey @khoivan88! I glad it was useful ❤️ 

Maybe you can submit a PR with a new option called `includeDoctype` that defaults to `true`?

**Comment by khoivan88** [comment]
hi @vimtor , I just created a PR. Hopefully it is the way you would like it. I'm new to JS so apology in advance for the poor coding!

Best

**Comment by vimtor** [comment]
Awesome! 👍
